### ISSUE TITLE
Hypertext link to manual on initial StoryCAD bootup leads to 404 page

### ISSUE THREAD

**Issue by SeanFager** [storybuilder-org/StoryCAD#557]
**Describe the bug**
Hypertext for new users prompting them to check the manual links to dead 404 page, https://storybuilder-org.github.io/StoryCAD-2/Quick_Start.html .  (The "?" icon linking to the manual does work as expected, linking to https://storybuilder-org.github.io/StoryCAD/ )

<img width="777" alt="01_SignInLinkDead" src="https://github.com/storybuilder-org/StoryCAD/assets/120670213/20dedcf0-e6ac-47e6-ac83-6f527211bf9d">

**To Reproduce**
1. Boot a fresh version of StoryCAD
2. Select the "Quick Start Guide" link in the popup during the Author personal data entry.

**Expected behavior**
The manual loads.

**Screenshots**
See above

**Supplemental information**
The root "https://storybuilder-org.github.io" also provides a 404 as of 16May2023

**Comment by Rarisma** [comment]
This was caused by the repo being renamed from StoryBuilder-2 to StoryCAD

The root URL leads to a 404 as there is no index to handle it, this isn't a large issue as the root will not show up in search results but StoryBuilder.org will. 
https://storybuilder-org.github.io/

However the following will work and the app will be updated to use it
https://storybuilder-org.github.io/StoryCAD
